### ISSUE TITLE
Part of answers are out of reach for some questions

### ISSUE THREAD

**Issue by WorldThirteen** [petulant-annie/millionaire-game#1]
I was curious to try this quite interesting game.
By the way, I was trapped in a case where part of the answers was not visible since were below the bottom point of the screen and I wasn't able to scroll to it.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/14346393/217100506-9dcd9859-32d7-40cb-b82b-d414f80ab6f4.png">

I am opening this issue to help enhance this game and give more fun to players. Looking forward to more questions.
P.S. Also looking forward for the final prize screen)

**Comment by petulant-annie** [comment]
Hey, thanks for your interest in this.
I'm aware of this problem and planned to fix it shortly. Actually, it's not finished yet. The only reason that it's public coz I wanted to try to publish it with gh-pages and check in-live.

**Comment by petulant-annie** [comment]
Answers visibility fixed, added sounds for more involvement to the game.

PS. I'd appreciate new comments or issues if you'd have one.
